# Generated by Django 4.1.7 on 2024-03-02 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statCName", models.CharField(max_length=20)),
                ("statEName", models.CharField(max_length=20)),
                ("provCname", models.CharField(max_length=20)),
                ("provEname", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_val", models.CharField(max_length=20)),
                ("weatehr_type_name", models.CharField(max_length=20)),
                (
                    "loc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_server.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_val", models.CharField(max_length=20)),
                ("crop_type_name", models.CharField(max_length=20)),
                (
                    "loc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_server.location",
                    ),
                ),
            ],
        ),
    ]
