# Generated by Django 4.1.7 on 2024-03-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop", name="crop_type", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crop", name="dvs", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="crop", name="lai", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="crop", name="tagp", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crop", name="wlv", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crop", name="wso", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crop", name="wst", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="location", name="lat", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="location", name="lon", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="location", name="statnum", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weather",
            name="precipitation",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weather",
            name="temperature",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weather",
            name="u_wind_speed",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weather",
            name="v_wind_speed",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weather",
            name="weather_type",
            field=models.IntegerField(default=0),
        ),
    ]
