# Generated by Django 4.1.7 on 2024-03-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_server",
            "0002_crop_crop_type_crop_dvs_crop_lai_crop_tagp_crop_wlv_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="weather",
            old_name="weatehr_type_name",
            new_name="weather_type_name",
        ),
    ]
