# Generated by Django 4.1.7 on 2024-04-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_server", "0004_rename_u_wind_speed_weather_wind_direction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weather",
            name="surface_solar_radiation",
            field=models.FloatField(default=0),
        ),
    ]
